name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Install
      run: npm install
    - name: Run tests
      run: npx hardhat test
